name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'

permissions:
  contents: read
  packages: read

jobs:
  xgov-delegator-contracts-validate:
    name: Run xgov-delegator-contracts release
    secrets: inherit
    uses: ./.github/workflows/xgov-delegator-contracts-ci.yaml

  xgov-delegator-contracts-release:
    name: Run xgov-delegator-contracts release
    secrets: inherit
    uses: ./.github/workflows/xgov-delegator-contracts-cd.yaml
    needs: xgov-delegator-contracts-validate

  xgov-delegator-frontend-validate:
    name: Run xgov-delegator-frontend release
    secrets: inherit
    uses: ./.github/workflows/xgov-delegator-frontend-ci.yaml

  xgov-delegator-frontend-release:
    name: Run xgov-delegator-frontend release
    secrets: inherit
    uses: ./.github/workflows/xgov-delegator-frontend-cd.yaml
    needs: xgov-delegator-frontend-validate
