name: Pull Request validation

on: [pull_request]


jobs:
  xgov-delegator-contracts-ci:
    name: Run xgov-delegator-contracts validation
    uses: ./.github/workflows/xgov-delegator-contracts-ci.yaml

  xgov-delegator-frontend-ci:
    name: Run xgov-delegator-frontend validation
    uses: ./.github/workflows/xgov-delegator-frontend-ci.yaml

